In [1]:
import numpy as np

# Define states and observations
states = ['S1=/f/', 'S2=/oʊ/', 'S3=/r/', 'S4=End']
num_states = len(states)

# Observation sequence
O = ['O1', 'O2', 'O3', 'O4']
T = len(O)  # Number of time steps

# Initialize delta and psi matrices
delta = np.zeros((num_states, T))  # Best path probabilities
psi = np.zeros((num_states, T), dtype=int)  # Backpointers for path reconstruction

# Answer for part (a)
print("=== Part (a): Initialization at t=1 ===")
print("General formula: δ₁(i) = π(i) * b_i(O₁)")
print("Where:")
print("  - π(i) is initial probability of state i")
print("  - b_i(O₁) is probability of observation O₁ given state i")
print("\nIn strictly ordered pronunciation model:")
print("δ₁(i) = 0 for all states except S1 because:")
print("1. π(S1) = 1 (we always start with /f/)")
print("2. π(i) = 0 for i ≠ S1 (cannot start with other phonemes)")
print("3. So δ₁(i) = 0 for i ≠ S1 regardless of b_i(O₁)")

=== Part (a): Initialization at t=1 ===
General formula: δ₁(i) = π(i) * b_i(O₁)
Where:
  - π(i) is initial probability of state i
  - b_i(O₁) is probability of observation O₁ given state i

In strictly ordered pronunciation model:
δ₁(i) = 0 for all states except S1 because:
1. π(S1) = 1 (we always start with /f/)
2. π(i) = 0 for i ≠ S1 (cannot start with other phonemes)
3. So δ₁(i) = 0 for i ≠ S1 regardless of b_i(O₁)


In [2]:
# Transition probabilities (a_ij = P(state j at t+1 | state i at t))
# Format: a[i][j] = probability from state i to state j
A = np.array([
    [0.0, 0.8, 0.0, 0.2],   # From S1: can go to S2 or End (with small prob)
    [0.0, 0.3, 0.6, 0.1],   # From S2: can go to S3 or stay or End
    [0.0, 0.0, 0.4, 0.6],   # From S3: can go to End or stay
    [0.0, 0.0, 0.0, 1.0]    # From End: absorbing state
])

# Observation probabilities (b_i(o) = P(observation o | state i))
# Format: b[state_index][observation_index]
B = np.array([
    [0.7, 0.2, 0.1, 0.0],   # S1 probabilities for O1, O2, O3, O4
    [0.1, 0.6, 0.2, 0.1],   # S2 probabilities
    [0.0, 0.2, 0.7, 0.1],   # S3 probabilities
    [0.0, 0.0, 0.0, 1.0]    # End probabilities
])

# Initial state probabilities
pi = np.array([1.0, 0.0, 0.0, 0.0])  # Only start with S1

print("Model Parameters:")
print(f"Transition matrix A:\n{A}")
print(f"\nEmission matrix B:\n{B}")
print(f"\nInitial probabilities π: {pi}")

Model Parameters:
Transition matrix A:
[[0.  0.8 0.  0.2]
 [0.  0.3 0.6 0.1]
 [0.  0.  0.4 0.6]
 [0.  0.  0.  1. ]]

Emission matrix B:
[[0.7 0.2 0.1 0. ]
 [0.1 0.6 0.2 0.1]
 [0.  0.2 0.7 0.1]
 [0.  0.  0.  1. ]]

Initial probabilities π: [1. 0. 0. 0.]
